from app.diffs.classification import (
    has_generated_marker,
    is_generated_or_vendor,
    is_lockfile,
    is_vendor_path,
    looks_binary_by_extension,
    parse_submodule_paths,
)


def test_is_lockfile_matches_known_names() -> None:
    assert is_lockfile("package-lock.json")
    assert is_lockfile("frontend/yarn.lock")
    assert not is_lockfile("app/models.py")


def test_is_vendor_path_matches_directory_segments() -> None:
    assert is_vendor_path("vendor/github.com/pkg/errors/errors.go")
    assert is_vendor_path("web/node_modules/react/index.js")
    assert not is_vendor_path("app/vendor_utils.py")


def test_looks_binary_by_extension() -> None:
    assert looks_binary_by_extension("assets/logo.png")
    assert looks_binary_by_extension("bin/tool.exe")
    assert not looks_binary_by_extension("app/main.py")
    assert not looks_binary_by_extension("Makefile")


def test_has_generated_marker_detects_common_phrases() -> None:
    assert has_generated_marker("// Code generated by protoc-gen-go. DO NOT EDIT.")
    assert has_generated_marker("<!-- @generated -->")
    assert not has_generated_marker("+def handler(request):")


def test_is_generated_or_vendor_combines_signals() -> None:
    assert is_generated_or_vendor("yarn.lock", None)
    assert is_generated_or_vendor("app/utils.min.js", None)
    assert is_generated_or_vendor("app/schema_pb2.py", None)
    assert is_generated_or_vendor("app/client.py", "// @generated by tool")
    assert not is_generated_or_vendor("app/client.py", "+regular change")


def test_parse_submodule_paths_extracts_paths() -> None:
    content = (
        '[submodule "libs/foo"]\n'
        "\tpath = libs/foo\n"
        "\turl = https://example.com/foo.git\n"
        '[submodule "libs/bar"]\n'
        "\tpath = libs/bar\n"
        "\turl = https://example.com/bar.git\n"
    )
    assert parse_submodule_paths(content) == {"libs/foo", "libs/bar"}


def test_parse_submodule_paths_handles_missing_or_invalid_content() -> None:
    assert parse_submodule_paths(None) == set()
    assert parse_submodule_paths("") == set()
    assert parse_submodule_paths("not an ini file {{{") == set()
