import configparser
import re

_LOCKFILE_NAMES = {
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "gemfile.lock",
    "poetry.lock",
    "pipfile.lock",
    "cargo.lock",
    "composer.lock",
    "uv.lock",
    "go.sum",
    "mix.lock",
}

_VENDOR_PATH_SEGMENTS = {
    "vendor",
    "node_modules",
    "dist",
    "build",
    ".next",
    "out",
    "generated",
    "__generated__",
    "third_party",
    "thirdparty",
}

_GENERATED_SUFFIXES = (
    ".min.js",
    ".min.css",
    ".pb.go",
    "_pb2.py",
    "_pb2_grpc.py",
    ".g.dart",
    ".generated.cs",
    ".designer.cs",
)

_BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tiff",
    ".pdf", ".zip", ".tar", ".gz", ".tgz", ".bz2", ".7z", ".rar",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".mp3", ".mp4", ".mov", ".avi", ".wav", ".flac",
    ".so", ".dll", ".dylib", ".exe", ".bin", ".class", ".jar", ".wasm",
    ".pyc", ".o", ".a",
    ".sqlite", ".db",
}

_GENERATED_MARKER = re.compile(
    r"@generated|do not edit|autogenerated|automatically generated|code generated by",
    re.IGNORECASE,
)


def is_lockfile(path: str) -> bool:
    return path.rsplit("/", 1)[-1].lower() in _LOCKFILE_NAMES


def is_vendor_path(path: str) -> bool:
    segments = {segment.lower() for segment in path.split("/")}
    return bool(segments & _VENDOR_PATH_SEGMENTS)


def has_generated_suffix(path: str) -> bool:
    lowered = path.lower()
    return lowered.endswith(_GENERATED_SUFFIXES)


def looks_binary_by_extension(path: str) -> bool:
    dot = path.rfind(".")
    if dot == -1:
        return False
    return path[dot:].lower() in _BINARY_EXTENSIONS


def has_generated_marker(patch: str) -> bool:
    """Cheap heuristic: many generated files declare themselves in the first
    few added lines (e.g. "// Code generated by ... DO NOT EDIT."). Only
    inspects patch text that is actually available.
    """
    return bool(_GENERATED_MARKER.search(patch))


def is_generated_or_vendor(path: str, patch: str | None) -> bool:
    if is_lockfile(path) or is_vendor_path(path) or has_generated_suffix(path):
        return True
    if patch and has_generated_marker(patch):
        return True
    return False


def parse_submodule_paths(gitmodules_content: str | None) -> set[str]:
    """Extract submodule `path = ...` entries from a .gitmodules file's content.

    Returns an empty set for missing/unparseable content rather than raising -
    submodule detection degrades to "none known" instead of crashing.
    """
    if not gitmodules_content or not gitmodules_content.strip():
        return set()

    parser = configparser.ConfigParser()
    try:
        parser.read_string(gitmodules_content)
    except configparser.Error:
        return set()

    paths: set[str] = set()
    for section in parser.sections():
        if parser.has_option(section, "path"):
            paths.add(parser.get(section, "path"))
    return paths
